"""Emit the C++ kernel's weights and a reference vector set to check it against.

The speed claim in this project is a hand-written kernel, not ONNX Runtime:
ORT costs 1788 + 98.0*b ns and the CKF is depth-first, so b = 1 and the fixed
term alone (1,886 ns) leaves 1.46x against RKN's 2,754 ns instead of 6.0x. So
the deployable form of g_theta is ~5,248 multiply-adds of Eigen, and this
script is what makes that port checkable rather than asserted:

  cpp/gtheta_weights.hpp   the three matrices, mu/sd, v1_scale, the sigma head
  cpp/reference.bin        N jumps of (input, expected output) from THIS file's
                           Python path, so `test_kernel` compares the C++
                           against the exact code every number in the report
                           came from
  cpp/field.bin            the ODD map as float32 Bz on its grid, which
                           bench_kernel needs in order to charge RKN for four
                           field reads per step and the kernel for one

    python export_kernel.py                     # -> all three, N = 2000
    python export_kernel.py --n 20000           # a wider net for the tolerance
    python export_kernel.py --no-field          # skip the 48 MB write

The defaults are the first teacher (gtheta_mat.npz). For the retrained one:

    python export_kernel.py --model gtheta_phys.npz --head sigma_head_phys.npz \
                            --pairs teacher_phys.parquet

and check the `source:` line the header carries. It is the only record of
which model the header holds.
"""
import argparse
import pathlib
import struct

import numpy as np
import polars as pl

from .chain_sim import cells
from .chi2_gate import ETA_EDGES, PT_EDGES
from .closed_loop import Model, features_plane, sigma_lookup
from .helix_variants import field_source
from .make_teacher_pairs import plane_predict

UM = 1e-3
OUT = pathlib.Path("cpp")

# The v1 scale table's shape, which is `LearnedNoise.hpp`'s binning and
# `train_gtheta.V1_CLASSES`. Written out here so a header built against a
# different binning fails the C++ static check rather than being mis-indexed.
kV1Class = 3
kV1Pt = len(PT_EDGES) - 1
kV1Eta = len(ETA_EDGES) - 1

# input  : x y z px py pz q  cx cy cz  nx ny nz  e0(3) e1(3)  bz_map sig0 sig1
# output : pos(3) mom(3) s ok m raw(6)
#
# The destination is the module PLANE, so the three numbers that used to
# describe it (r1, z1, endcap) are replaced by the module's centre, normal and
# two local axes. Fifteen numbers instead of three, and all fifteen come from
# the geometry rather than from the answer.
N_IN, N_OUT_REF = 22, 15


# The kernel's six outputs, in order. 0 and 1 are the in-plane position
# correction, 2 to 4 the direction and q/p, 5 the sigma head.
OUTPUTS = ("loc0", "loc1", "phi", "theta", "qop", "sigma")


def cxx_array(name, a, per_line=6):
    """A flat inline constexpr array. Row-major, printed to full precision so
    the header is the weights rather than an approximation of them."""
    flat = np.asarray(a, dtype=np.float64).ravel()
    body = []
    for i in range(0, len(flat), per_line):
        body.append("    " + ", ".join(f"{v: .17e}" for v in flat[i:i + per_line]))
    return (f"inline constexpr double {name}[{len(flat)}] = {{\n"
            + ",\n".join(body) + "\n};\n")


def write_header(model_path, head_path, out, zero=()):
    d = np.load(model_path, allow_pickle=False)
    h = np.load(head_path, allow_pickle=False)
    act = str(d["act"][0])
    if act != "ptanh":
        raise SystemExit(f"kernel implements ptanh only, model says {act!r}")
    nin, nh, nout = int(d["meta"][1]), int(d["meta"][0]), int(d["meta"][2])

    # An output is removed at the last layer, by
    # zeroing its column of W2 and its entry of b2, so `raw[k]` is identically
    # zero and every use of it downstream is switched off at once. It is done
    # here rather than by zeroing `v1_scale` because outputs 0 and 1 have no
    # scale constant to zero: their scale is the per-jump sigma the caller
    # supplies. The effect on outputs 2 to 4 is the same either way, since the
    # kernel forms `helix + raw[k] * v1_scale[k]`.
    d = dict(d)
    for k in zero:
        d["W2"] = d["W2"].copy()
        d["b2"] = d["b2"].copy()
        d["W2"][:, k] = 0.0
        d["b2"][k] = 0.0

    note = ""
    if zero:
        note = (", outputs " + ",".join(OUTPUTS[k] for k in sorted(zero))
                + " zeroed, not for shipping)")
    s = [
        "// Generated by export_kernel.py -- do not edit.",
        f"// source: {model_path}, {head_path}{note}",
        "//",
        "// Row-major. W0 is [nin][nh], W1 [nh][nh], W2 [nh][nout], so the",
        "// forward pass is x*W with the same index order as the numpy code.",
        "#pragma once",
        "namespace collider_ml::weights {",
        "",
        f"inline constexpr int kNIn = {nin};",
        f"inline constexpr int kNHidden = {nh};",
        f"inline constexpr int kNOut = {nout};",
        "",
    ]
    for k in ("W0", "W1", "W2", "b0", "b1", "b2", "mu", "sd", "v1_scale"):
        s.append(cxx_array(k, d[k]))

    # The scale outputs 2 to 4 are applied with, per (class, pT bin, |eta| bin).
    # `v1_scale` above stays because it is what a jump on a volume the runtime
    # cannot classify falls back to, and because it is the number every earlier
    # model is recorded by.
    #
    # A model fitted before `train_gtheta.py` grew the table, or one fitted with
    # `--v1-global`, has every cell equal to that triple, so the table is exact
    # in both cases and the C++ needs no branch. Broadcasting here rather than
    # in the kernel keeps the header a complete statement of the model.
    # `d` is a plain dict from the zeroing block above, so membership is
    # `in d` and not `in d.files`. An NpzFile was what this read when it
    # was written, and the mistake was silent until a model that HAS the
    # table was exported.
    cell = d["v1_scale_cell"] if "v1_scale_cell" in d else None
    if cell is None:
        cell = np.tile(np.asarray(d["v1_scale"]),
                       (kV1Class, kV1Pt, kV1Eta, 1))
        s.append("// v1_scale_cell: broadcast from the global triple. This "
                 "model predates the\n// per-cell scale, so every cell is the "
                 "same and the runtime behaviour is unchanged.\n")
    if np.shape(cell) != (kV1Class, kV1Pt, kV1Eta, 3):
        raise SystemExit(f"v1_scale_cell is {np.shape(cell)}, the kernel "
                         f"expects ({kV1Class}, {kV1Pt}, {kV1Eta}, 3)")
    s.append(f"inline constexpr int kV1Class = {kV1Class};")
    s.append(f"inline constexpr int kV1Pt = {kV1Pt};")
    s.append(f"inline constexpr int kV1Eta = {kV1Eta};\n")
    s.append(cxx_array("v1_scale_cell", cell))
    s.append(cxx_array("head_w", h["w"]))
    s.append(f"inline constexpr double head_b = {float(h['b'][0]): .17e};\n")
    s.append("}  // namespace collider_ml::weights")
    out.write_text("\n".join(s))
    return nin, nh, nout


def reference(pairs, model, fm, siglook, n, seed, head):
    """Run the production Python path on n jumps and record both ends of it.

    What this does not cover. The reference applies `model.v1_scale`, the global
    triple, and `cpp/test_kernel.cpp` builds a `Jump` without setting `v1s`, so
    it gets the same triple from the struct's default. The two therefore agree
    by construction and `test_kernel` stays a test of the forward pass and the
    weights, which is what it is for.

    It is not a test of the per-cell scale. `LearnedStepper::toJump` is the only
    thing that fills `Jump::v1s` from `v1_scale_cell`, so a model fitted with
    the per-cell scale is exercised by a CKF arm and by nothing else. A green
    `test_kernel` says the weights shipped, not that the scale is being looked
    up. `cpp/geom_probe` and the run's own census are where that shows.
    """
    t = pl.read_parquet(pairs)
    rng = np.random.default_rng(seed)
    idx = rng.choice(len(t), size=min(n, len(t)), replace=False)
    t = t[np.sort(idx)]

    u = np.column_stack([t[c].to_numpy() for c in
                         ("x", "y", "z", "px", "py", "pz")])
    q = np.sign(t["qop"].to_numpy())
    r1 = t["r1"].to_numpy()
    z1 = t["z1"].to_numpy()
    endcap = t["endcap"].to_numpy().astype(bool)

    # the cell sigma the position outputs are written in; a table lookup in
    # Python and a caller-supplied number in C++, because in ACTS it comes
    # from the calibration context rather than from a table here
    vol = t["surf1"].to_numpy() >> 56
    ip, ie = cells(t["pt"].to_numpy(), t["abs_eta"].to_numpy())
    sig = np.array([siglook(vol[i], ip[i], ie[i])[:2] for i in range(len(t))])

    # The destination is the module plane the table already names, and the
    # helix is solved onto it with the same Newton the kernel runs.
    cen = np.column_stack([t["mc_x"], t["mc_y"], t["mc_z"]]).astype(float)
    nrm = np.column_stack([t["mn_x"], t["mn_y"], t["mn_z"]]).astype(float)
    e0 = np.column_stack([t["mu0_x"], t["mu0_y"], t["mu0_z"]]).astype(float)
    e1 = np.column_stack([t["mu1_x"], t["mu1_y"], t["mu1_z"]]).astype(float)

    hx, hy, hz, hmx, hmy, hmz, s_arc, ok = plane_predict(
        u[:, 0], u[:, 1], u[:, 2], u[:, 3], u[:, 4], u[:, 5], q, 2.0, cen, nrm)
    hpos = np.column_stack([hx, hy, hz])
    hmom = np.column_stack([hmx, hmy, hmz])

    p = np.linalg.norm(u[:, 3:], axis=1)
    qop = q / p
    X = features_plane(u, qop, cen, nrm, e0, e1, hpos, fm)
    pred, hid = model.forward_hidden((X - model.mu) / model.sd)

    pb = pred[:, :2] * sig
    pos = hpos - (pb[:, :1] * UM) * e0 - (pb[:, 1:2] * UM) * e1

    hp = np.linalg.norm(hmom, axis=1)
    phi_h = np.arctan2(hmom[:, 1], hmom[:, 0])
    th_h = np.arctan2(np.hypot(hmom[:, 0], hmom[:, 1]), hmom[:, 2])
    phi_c = phi_h + pred[:, 2] * model.v1_scale[0]
    th_c = th_h + pred[:, 3] * model.v1_scale[1]
    qop_c = qop + pred[:, 4] * model.v1_scale[2]
    pc = np.abs(1.0 / np.where(np.abs(qop_c) < 1e-9,
                               np.sign(qop_c) * 1e-9, qop_c))
    mom = np.column_stack([pc * np.sin(th_c) * np.cos(phi_c),
                           pc * np.sin(th_c) * np.sin(phi_c),
                           pc * np.cos(th_c)])

    # Not a hard-coded "sigma_head.npz". write_header() emits whatever --head
    # points at, so reading a different file here would put one head in the C++
    # and a different one in the vectors the C++ is checked against -- and the
    # only symptom would be test_kernel disagreeing on m alone, which reads as
    # a porting bug in the sigma head rather than as two different heads.
    hw = np.load(head, allow_pickle=False)
    m = np.exp(hid @ hw["w"] + float(hw["b"][0]))

    bz = fm.bz(u[:, 0], u[:, 1], u[:, 2])
    inp = np.column_stack([u, q, cen, nrm, e0, e1, bz, sig])
    exp = np.column_stack([pos, mom, s_arc, ok.astype(float), m, pred])
    assert inp.shape[1] == N_IN and exp.shape[1] == N_OUT_REF
    return inp, exp


def write_field(npz_path, out):
    """The ODD map, flattened for the C++ benchmark.

    Bz only and float32, because the benchmark needs the CACHE BEHAVIOUR of a
    real 201x201x301 lookup rather than the values -- what it is measuring is
    that RKN4 reads the field four times per step and the learned jump reads it
    once. Header is (nx, ny, nz) int32 then origin[3], step[3] as float64.
    """
    d = np.load(npz_path)
    x, y, z = d["x"], d["y"], d["z"]
    nx, ny, nz = len(x), len(y), len(z)
    bz = d["B"].reshape(nx, ny, nz, 3)[..., 2].astype("<f4")
    with open(out, "wb") as f:
        f.write(struct.pack("<iii", nx, ny, nz))
        f.write(struct.pack("<6d", x[0], y[0], z[0],
                            x[1] - x[0], y[1] - y[0], z[1] - z[0]))
        f.write(bz.tobytes())
    print(f"cpp/field.bin            {nx}x{ny}x{nz}, "
          f"{out.stat().st_size / 1e6:.1f} MB")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pairs", default="teacher_map_mat_logpt.parquet")
    ap.add_argument("--model", default="gtheta_mat.npz")
    ap.add_argument("--head", default="sigma_head.npz")
    ap.add_argument("--field", default="/tmp/oddb.npz")
    ap.add_argument("--cov", default="sigma_C.parquet")
    ap.add_argument("--digi", default="odd-digi-smearing-config.json")
    ap.add_argument("--no-field", action="store_true",
                    help="skip cpp/field.bin (48 MB) if it is already there")
    ap.add_argument("--zero-outputs", default="",
                    help="comma separated list of outputs to remove, from "
                         + ",".join(OUTPUTS) + ". "
                         "Writes the header and nothing else: a reference set "
                         "generated against a crippled model is not the "
                         "production one, and the header it leaves behind must "
                         "not ship, so restore it with "
                         "`git checkout cpp/gtheta_weights.hpp` afterwards")
    ap.add_argument("--zero-v1", action="store_true",
                    help="shorthand for --zero-outputs phi,theta,qop")
    ap.add_argument("--n", type=int, default=2000)
    ap.add_argument("--seed", type=int, default=20260810)
    a = ap.parse_args()

    names = [s.strip() for s in a.zero_outputs.split(",") if s.strip()]
    if a.zero_v1:
        names += ["phi", "theta", "qop"]
    bad = [n for n in names if n not in OUTPUTS]
    if bad:
        raise SystemExit(f"unknown output{'s' if len(bad) > 1 else ''} "
                         f"{','.join(bad)}; known are {','.join(OUTPUTS)}")
    zero = sorted({OUTPUTS.index(n) for n in names})

    OUT.mkdir(exist_ok=True)
    nin, nh, nout = write_header(a.model, a.head, OUT / "gtheta_weights.hpp",
                                 zero=zero)
    print(f"cpp/gtheta_weights.hpp   {nin}-{nh}-{nh}-{nout}"
          + (f"   ZEROED {','.join(OUTPUTS[k] for k in zero)}" if zero else ""))
    if zero:
        print("  header only. restore with "
              "`git checkout cpp/gtheta_weights.hpp` when the run is done")
        return

    model = Model(a.model)
    if model.field != a.field:
        print(f"  note: model was trained with field={model.field!r}")
    fm = field_source(a.field)
    inp, exp = reference(a.pairs, model, fm, sigma_lookup(a.cov, a.digi),
                         a.n, a.seed, a.head)

    with open(OUT / "reference.bin", "wb") as f:
        f.write(struct.pack("<iii", len(inp), N_IN, N_OUT_REF))
        f.write(inp.astype("<f8").tobytes())
        f.write(exp.astype("<f8").tobytes())
    print(f"cpp/reference.bin        {len(inp)} jumps, "
          f"{N_IN} in / {N_OUT_REF} out")
    print(f"  arc length valid in {100 * exp[:, 7].mean():.1f}% of them")

    if not a.no_field:
        write_field(a.field, OUT / "field.bin")


if __name__ == "__main__":
    main()
