"""Are the network's inputs, as the CKF builds them, inside the distribution the
model was fitted on.

The port is tested and the caller is not. `cpp/test_kernel.cpp` compares the C++
forward pass against reference vectors generated by the Python path, and both
sides of that comparison are in the training units, so an error in the code that
*builds* the input vector at run time is invisible to it. One lived there for a
month: the field feature was filled straight from `getField`, which answers in
ACTS units, so a 2 T solenoid reached the network ten standard deviations below
its training mean on every jump. Every other input has the same exposure.

This is the check that closes that. `cpp/FeatureDump.hpp` writes the raw feature
vectors at the point they enter `forward()`; this reads them against the `mu`
and `sd` that `train_gtheta.py` stored beside the weights, and prints one row
per input.

    FEATURE_DUMP=/output/runs/x/features.bin \\
        sim/run_reco_ckf.sh <sample> <subdir> learned-on <qtable>
    python -m prop.feature_check ~/baseline0/out/runs/x/features.bin \\
        --model ~/exp/B/gtheta_B.npz

The verdict is per input and it is an offset, not a p-value: `(run median -
training mean) / training sd`. A real distribution shift between a training
sample and an evaluation sample moves a feature by a fraction of a standard
deviation. Anything past `--tol` (three by default) is a defect in the code that
builds the vector, and the exit status says so, so this can stand in front of a
measurement rather than beside it.
"""
import argparse
import pathlib
import struct
import sys

import numpy as np

# The fourteen inputs in the order `LearnedTransport.hpp:features()` writes
# them and `train_gtheta.py:inputs()` stacks them. The two orders are the same
# by construction and this list is the only place the names live.
NAMES = (
    "r0, source radius [mm]",
    "z, source z [mm]",
    "p_r, momentum along r_hat [GeV]",
    "p_phi, momentum along phi_hat [GeV]",
    "p_z [GeV]",
    "q/p [1/GeV]",
    "path to the module plane [mm]",
    "|cos| of the incidence angle",
    "helix answer along e0 [mm]",
    "helix answer along e1 [mm]",
    "Bz at the source [T]",
    "|n_z| of the module",
    "e0 against phi_hat at the module centre",
    "e0_z",
)


def read_dump(path):
    """(rows, cols) float64 from cpp/FeatureDump.hpp, plus the offered count.

    The row count in the header is patched in at exit, so a run that died holds
    a zero there. The file size is the authority and the header is the check:
    `cols` is written when the file is opened and is always right.
    """
    raw = pathlib.Path(path).read_bytes()
    if len(raw) < 16:
        raise SystemExit(f"{path}: {len(raw)} bytes, not a feature dump")
    rows, cols = struct.unpack("<ii", raw[:8])
    (offered,) = struct.unpack("<q", raw[8:16])
    body = len(raw) - 16
    if cols <= 0 or body % (8 * cols):
        raise SystemExit(f"{path}: {body} bytes of body is not a whole number "
                         f"of {cols}-wide rows")
    n = body // (8 * cols)
    if rows != n:
        print(f"  note: header says {rows} rows, the file holds {n}. "
              "The run did not close the dump; reading the file.")
    x = np.frombuffer(raw[16:], dtype="<f8").reshape(n, cols)
    return x, offered


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("dump", nargs="+",
                    help="the files FEATURE_DUMP named. More than one is "
                         "pooled, which is how a check that has to cover the "
                         "whole pT range is run: one short run per bin")
    ap.add_argument("--model", required=True,
                    help="the .npz the run's weights were exported from; mu "
                         "and sd come from it")
    ap.add_argument("--tol", type=float, default=3.0,
                    help="offset in training sd past which an input is called "
                         "a defect rather than a shift")
    a = ap.parse_args()

    d = np.load(a.model, allow_pickle=False)
    mu, sd = d["mu"], d["sd"]
    parts, offered = [], 0
    for path in a.dump:
        xi, oi = read_dump(path)
        parts.append(xi)
        offered += oi
    x = np.concatenate(parts, axis=0)

    if x.shape[1] != len(mu):
        raise SystemExit(f"the dump is {x.shape[1]} wide and {a.model} was "
                         f"fitted on {len(mu)} inputs")
    names = NAMES if len(mu) == len(NAMES) else \
        tuple(f"input {i}" for i in range(len(mu)))

    denom = np.where(sd > 0, sd, 1.0)
    med = np.median(x, axis=0)
    p10, p90 = np.percentile(x, 10, axis=0), np.percentile(x, 90, axis=0)
    off = (med - mu) / denom

    print()
    for path, xi in zip(a.dump, parts):
        print(f"  {path}   {xi.shape[0]:,} rows")
    print(f"  {x.shape[0]:,} input vectors pooled, of {offered:,} the runs "
          f"built, {x.shape[1]} wide")
    print(f"  training mean and sd from {a.model}\n")

    w = max(len(s) for s in names)
    print(f"| {'':>2} | {'input':<{w}} | {'train mean':>12} | {'train sd':>11} "
          f"| {'run median':>12} | {'run p10':>12} | {'run p90':>12} "
          f"| {'offset [sd]':>11} | {'spread':>7} |")
    print(f"| {'-' * 2} | {'-' * w} | {'-' * 12} | {'-' * 11} | {'-' * 12} "
          f"| {'-' * 12} | {'-' * 12} | {'-' * 11} | {'-' * 7} |")
    for i, nm in enumerate(names):
        print(f"| {i:>2} | {nm:<{w}} | {mu[i]:>12.6g} | {sd[i]:>11.6g} "
              f"| {med[i]:>12.6g} | {p10[i]:>12.6g} | {p90[i]:>12.6g} "
              f"| {off[i]:>+11.2f} | {x[:, i].std() / denom[i]:>7.3f} |")
    print("\n  `spread` is the run's own standard deviation over the training "
          "one. It carries no threshold\n  and it is not the same question as "
          "the offset: an input can sit on the training mean and\n  still be "
          "confined to a sliver of the range the fit saw, or run far wider "
          "than it.")

    # Per run as well as pooled. Pooling five pT bins averages an input that is
    # only wrong in one of them back inside the tolerance, and the first thing
    # this check found after the field feature was fixed was exactly that.
    worst = np.abs(off)
    if len(parts) > 1:
        each = np.array([(np.median(p, axis=0) - mu) / denom for p in parts])
        worst = np.maximum(worst, np.abs(each).max(axis=0))
        print("\n  offset of the median in each dump on its own, "
              "same units:\n")
        labels = [pathlib.Path(p).parent.name for p in a.dump]
        cw = max(8, max(len(s) for s in labels))
        head = "  ".join(f"{s:>{cw}}" for s in labels)
        print(f"  {'':>2}  {'':<{w}}  {head}")
        for i, nm in enumerate(names):
            row = "  ".join(f"{v:>+{cw}.2f}" for v in each[:, i])
            print(f"  {i:>2}  {nm:<{w}}  {row}")

    bad = np.flatnonzero(worst > a.tol)
    print()
    if bad.size == 0:
        print(f"  all {len(mu)} inputs are within {a.tol:g} sd of their "
              "training mean, pooled and in every dump.")
        return 0
    print(f"  {bad.size} of {len(mu)} inputs are more than {a.tol:g} sd off. "
          "An input that far out is not a\n  distribution shift, and no "
          "learned-on number taken with it is usable until it is\n  explained:")
    for i in bad:
        print(f"    {i:>2}  {names[i]:<{w}}  {worst[i]:.1f} sd at worst")
    return 1


if __name__ == "__main__":
    sys.exit(main())
